const constants = {
  dashboard: {
    greeting: "Hello",
    heroText: "You're doing great this week. Keep it up!",
    sectionHeadings: ["Statistics", "My Courses", "Continue To Learn"],
    statistics: {
      coursesCompleted: "Courses Completed",
      progress: "Courses in Progress",
      selectdate: "Select Range",
      daysToPresentInChart: 14,
    },
  },
  enterEmailMessage: "Enter the email address associated with your account.",
  Forgot: "Forgot",
  Password: "Password",
  BackTo: "Back to",
  SignIn: " Sign In",
  Submit: " Submit",
  SignUp: " Sign Up",
  WelcomeBack: "Welcome back",
  SignInTo: "Sign in to ",
  YourAccount: "your account",
  ForgotPassword: "Forgot Password?",
  SignInNow: " Sign in now",
  SignInGoogle: "Or sign in with google",
  DoNotHaveAccount: " Don't have account",
  SavePassword: "Save Password",
  selectDate: "select date",
  Resetyour: "Reset your",
  Previous: "Previous",
  NextStep: " Next Step",
  SignUpto: "Sign up to",
  AlreadyHaveAccount: "Already have an account",
  HighlightText: "Highlight Text",
  CommentText: "Comment Text",
  Download: "Download Syllabus",
  Print: "Print out Syllabus",
  courses: "Courses",
  ExpandAllUnits: "Expand all units",
  learningResources: {
    syllabus: {
      highlightTooltip: "Mark text to highlight",
      commentTooltip: "Mark text to Comment",
      printTooltip: "Print Out Syllabus",
      downloadTooltip: "Download Syllabus",
      syllabus: "Syllabus",
    },
  },
  timeInterval: [
    "This week",
    "This month",
    "Previous week",
    "Previous month",
    "Last three months",
  ],
  profession: ["Teacher", "Student"],
};

export default constants;
